/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/crisis-list.component';
const styles_CrisisListComponent:any[] = ([] as any[]);
export const RenderType_CrisisListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CrisisListComponent,
  data: {}
}
);
export function View_CrisisListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['CRISIS CENTER'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Get your crisis here']))
  ]
  ,(null as any),(null as any));
}
function View_CrisisListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_CrisisListComponent_0,RenderType_CrisisListComponent)),
    import0.ɵdid(24576,(null as any),0,import1.CrisisListComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CrisisListComponentNgFactory:import0.ComponentFactory<import1.CrisisListComponent> = import0.ɵccf('ng-component',import1.CrisisListComponent,View_CrisisListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ09NSS9Eb2N1bWVudHMvR2l0SHViL25nLXNpbXBsZS1kZXBsb3ltZW50L3NyYy9hcHAvY3Jpc2lzLWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0NPTUkvRG9jdW1lbnRzL0dpdEh1Yi9uZy1zaW1wbGUtZGVwbG95bWVudC9zcmMvYXBwL2NyaXNpcy1saXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0NPTUkvRG9jdW1lbnRzL0dpdEh1Yi9uZy1zaW1wbGUtZGVwbG95bWVudC9zcmMvYXBwL2NyaXNpcy1saXN0LmNvbXBvbmVudC50cy5DcmlzaXNMaXN0Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9DT01JL0RvY3VtZW50cy9HaXRIdWIvbmctc2ltcGxlLWRlcGxveW1lbnQvc3JjL2FwcC9jcmlzaXMtbGlzdC5jb21wb25lbnQudHMuQ3Jpc2lzTGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxoMj5DUklTSVMgQ0VOVEVSPC9oMj5cbiAgICA8cD5HZXQgeW91ciBjcmlzaXMgaGVyZTwvcD4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUNJO0lBQUk7SUFBa0I7SUFDdEI7SUFBRzs7Ozs7O0lDRlA7Z0JBQUE7Ozs7In0=
