/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/app/hero-list.component';
const styles_HeroListComponent:any[] = ([] as any[]);
export const RenderType_HeroListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HeroListComponent,
  data: {}
}
);
export function View_HeroListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['HEROES'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Get your heroes here'])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_HeroListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_HeroListComponent_0,RenderType_HeroListComponent)),
    import0.ɵdid(24576,(null as any),0,import1.HeroListComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HeroListComponentNgFactory:import0.ComponentFactory<import1.HeroListComponent> = import0.ɵccf('ng-component',import1.HeroListComponent,View_HeroListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ09NSS9Eb2N1bWVudHMvR2l0SHViL25nLXNpbXBsZS1kZXBsb3ltZW50L3NyYy9hcHAvaGVyby1saXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9DT01JL0RvY3VtZW50cy9HaXRIdWIvbmctc2ltcGxlLWRlcGxveW1lbnQvc3JjL2FwcC9oZXJvLWxpc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvQ09NSS9Eb2N1bWVudHMvR2l0SHViL25nLXNpbXBsZS1kZXBsb3ltZW50L3NyYy9hcHAvaGVyby1saXN0LmNvbXBvbmVudC50cy5IZXJvTGlzdENvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQ09NSS9Eb2N1bWVudHMvR2l0SHViL25nLXNpbXBsZS1kZXBsb3ltZW50L3NyYy9hcHAvaGVyby1saXN0LmNvbXBvbmVudC50cy5IZXJvTGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxoMj5IRVJPRVM8L2gyPlxuICAgIDxwPkdldCB5b3VyIGhlcm9lcyBoZXJlPC9wPlxuICAiLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUNJO0lBQUk7SUFBVztJQUNmO0lBQUc7SUFBd0I7Ozs7OztJQ0YvQjtnQkFBQTs7OzsifQ==
